import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Set;

/**
 * Generates IBM-937 SBCS and DBCS encoding tables as TypeScript source.
 * Requires IBM Semeru or any JVM with IBM-937 (Cp937) charset support.
 *
 * Usage:
 *   javac -encoding UTF-8 TableGenerator.java
 *   java TableGenerator > ../src/codec/tables.ts
 */
public class TableGenerator {
    private static final int SO = 0x0E;
    private static final int SI = 0x0F;

    public static void main(String[] args) throws Exception {
        Charset ibm937 = null;
        for (String name : new String[]{"IBM937", "Cp937", "x-IBM937"}) {
            try {
                ibm937 = Charset.forName(name);
                break;
            } catch (Exception ignored) {}
        }
        if (ibm937 == null) {
            System.err.println("ERROR: IBM-937 charset not available");
            System.exit(1);
        }

        PrintWriter out = new PrintWriter(new OutputStreamWriter(System.out, StandardCharsets.UTF_8));
        out.println("// @ts-nocheck");
        out.println("// AUTO-GENERATED by scripts/TableGenerator.java — do not edit manually.");
        out.println("// Generated from IBM-937 (Cp937) JVM charset.");
        out.println();

        // ----------------------------------------------------------------
        // SBCS table: byte 0x00-0xFF → Unicode codepoint
        // ----------------------------------------------------------------
        out.println("/** SBCS byte (0x00-0xFF) → Unicode code point. Index is the EBCDIC byte value. */");
        out.println("export const SBCS_TO_UNICODE: readonly number[] = [");

        CharsetDecoder sbcsDecoder = ibm937.newDecoder()
                .onMalformedInput(CodingErrorAction.REPLACE)
                .onUnmappableCharacter(CodingErrorAction.REPLACE);

        for (int b = 0; b <= 255; b++) {
            ByteBuffer bb = ByteBuffer.wrap(new byte[]{(byte) b});
            CharBuffer cb = sbcsDecoder.decode(bb);
            int cp = cb.length() > 0 ? cb.charAt(0) : 0xFFFD;
            String comment = isPrint(cp) ? String.valueOf((char) cp) : String.format("U+%04X", cp);
            out.printf("  0x%04X, // 0x%02X  %s%n", cp, b, comment);
        }
        out.println("];");
        out.println();

        // ----------------------------------------------------------------
        // DBCS table: (b1<<8|b2) → Unicode codepoint
        // ----------------------------------------------------------------
        out.println("/**");
        out.println(" * DBCS pair → Unicode code point.");
        out.println(" * Key = (firstByte << 8) | secondByte. Only valid pairs are present.");
        out.println(" */");
        out.println("export const DBCS_TO_UNICODE: Record<number, number> = {");

        CharsetDecoder dbcsDecoder = ibm937.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT);

        int count = 0;
        for (int b1 = 0x40; b1 <= 0xFE; b1++) {
            for (int b2 = 0x40; b2 <= 0xFE; b2++) {
                byte[] wrapped = new byte[]{(byte) SO, (byte) b1, (byte) b2, (byte) SI};
                try {
                    CharBuffer cb = dbcsDecoder.decode(ByteBuffer.wrap(wrapped));
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < cb.length(); i++) {
                        char c = cb.charAt(i);
                        if (c != SO && c != SI) sb.append(c);
                    }
                    String decoded = sb.toString();
                    if (decoded.length() == 1) {
                        int cp = decoded.codePointAt(0);
                        if (cp > 0x7E) {
                            int key = (b1 << 8) | b2;
                            out.printf("  0x%04X: 0x%04X, // %s%n", key, cp, decoded);
                            count++;
                        }
                    }
                } catch (Exception ignored) {
                    // Invalid DBCS pair
                }
            }
        }
        out.println("};");
        out.println();

        // ----------------------------------------------------------------
        // Reverse DBCS table: Unicode codepoint → DBCS pair key
        // IBM-937 may have multiple DBCS pairs mapping to the same Unicode
        // codepoint. We keep only the first (canonical) mapping.
        // ----------------------------------------------------------------
        out.println("/**");
        out.println(" * Unicode code point → DBCS pair key ((b1<<8)|b2).");
        out.println(" * Only contains characters that have a DBCS encoding in IBM-937.");
        out.println(" */");
        out.println("export const UNICODE_TO_DBCS: Record<number, number> = {");

        Set<Integer> seenDbcs = new HashSet<>();
        for (int b1 = 0x40; b1 <= 0xFE; b1++) {
            for (int b2 = 0x40; b2 <= 0xFE; b2++) {
                byte[] wrapped = new byte[]{(byte) SO, (byte) b1, (byte) b2, (byte) SI};
                try {
                    CharBuffer cb = dbcsDecoder.decode(ByteBuffer.wrap(wrapped));
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < cb.length(); i++) {
                        char c = cb.charAt(i);
                        if (c != SO && c != SI) sb.append(c);
                    }
                    String decoded = sb.toString();
                    if (decoded.length() == 1) {
                        int cp = decoded.codePointAt(0);
                        if (cp > 0x7E && !seenDbcs.contains(cp)) {
                            seenDbcs.add(cp);
                            int key = (b1 << 8) | b2;
                            out.printf("  0x%04X: 0x%04X, // %s%n", cp, key, decoded);
                        }
                    }
                } catch (Exception ignored) {}
            }
        }
        out.println("};");
        out.println();

        // ----------------------------------------------------------------
        // Reverse SBCS table: Unicode codepoint → SBCS byte
        // Keep only the first mapping when a Unicode char has multiple SBCS bytes.
        // ----------------------------------------------------------------
        out.println("/**");
        out.println(" * Unicode code point → SBCS byte.");
        out.println(" * Only contains characters that have an SBCS encoding in IBM-937.");
        out.println(" */");
        out.println("export const UNICODE_TO_SBCS: Record<number, number> = {");

        Set<Integer> seenSbcs = new HashSet<>();
        for (int b = 0; b <= 255; b++) {
            if (b == SO || b == SI) continue;
            ByteBuffer bb = ByteBuffer.wrap(new byte[]{(byte) b});
            try {
                CharBuffer cb = sbcsDecoder.decode(bb);
                if (cb.length() > 0) {
                    int cp = cb.charAt(0);
                    if (cp != 0xFFFD && !seenSbcs.contains(cp)) {
                        seenSbcs.add(cp);
                        out.printf("  0x%04X: 0x%02X, // %s%n", cp, b,
                                isPrint(cp) ? String.valueOf((char) cp) : String.format("U+%04X", cp));
                    }
                }
            } catch (Exception ignored) {}
        }
        out.println("};");
        out.println();

        out.printf("// Total DBCS pairs: %d%n", count);
        out.flush();
        System.err.printf("Generated %d DBCS pairs.%n", count);
    }

    private static boolean isPrint(int cp) {
        return cp >= 0x20 && cp < 0x7F || cp > 0xA0 && cp < 0xFFFD;
    }
}
